---
platform: linux

image: docker:///flintstonecf/ci

inputs:
- name: git-bits-service-release
- name: bits-service-release-version

params:
  VERSION_FILE:

outputs:
- name: releases

run:
  path: git-bits-service-release/ci/scripts/create-bits-release.sh
