---
platform: linux

image: docker:///flintstonecf/ci

inputs:
- name: git-bits-service-release
- name: bits-service-release-version

params:
  BOSH_TARGET:
  BOSH_USERNAME:
  BOSH_PASSWORD:
  BITS_DIRECTORY_KEY:
  BITS_AWS_REGION:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  BLOBSTORE_TYPE:
  VERSION_FILE: ../bits-service-release-version/number

outputs:
- name: manifests

run:
  path: git-bits-service-release/ci/scripts/create-bits-manifest.sh
