---
platform: linux

image: docker:///flintstonecf/ci

params:
  VERSION_FILE: ../cf-release-version/number
  MANIFEST_STUBS:
  IAAS: lite

inputs:
- name: git-bits-service-release
- name: cf-release-version

outputs:
- name: manifests

run:
  path: git-bits-service-release/ci/scripts/update-cf-manifest.sh
