networks:
- name: cf_private
  type: manual
  subnets:
  - range: 10.10.160.0/24
    gateway: 10.10.160.1
    dns: [10.10.0.2]
    reserved: ["10.10.160.2 - 10.10.160.3"]
    static: ["10.10.160.100 - 10.10.160.105"]
    cloud_properties:
      subnet: subnet-1608e74e

- name: cf_public
  type: manual
  subnets:
  - range: 10.10.180.0/24
    gateway: 10.10.180.1
    dns: [10.10.0.2]
    reserved: ["10.10.180.2 - 10.10.180.10"]
    cloud_properties:
      subnet: subnet-6a65cb0e
      security_groups:
        - sg-2ca8514b
        - sg-4fa95028
