networks:
- name: cf_private
  type: manual
  subnets:
  - range: 10.10.16.0/24
    gateway: 10.10.16.1
    dns: [10.10.0.2]
    reserved: ["10.10.16.2 - 10.10.16.3"]
    static: ["10.10.16.100 - 10.10.16.105"]
    cloud_properties:
      subnet: subnet-56faf00f

- name: cf_public
  type: manual
  subnets:
  - range: 10.10.80.0/24
    gateway: 10.10.80.1
    dns: [10.10.0.2]
    reserved: ["10.10.80.2 - 10.10.80.10"]
    cloud_properties:
      subnet: subnet-6a39ec0e
      security_groups:
        - sg-2ca8514b
        - sg-4fa95028
